# Generated by Django 5.1 on 2024-08-28 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0003_loginactivity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginactivity',
            old_name='user',
            new_name='name',
        ),
    ]
