# Generated by Django 5.1 on 2024-09-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0005_loginactivity_logout_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('bot_response', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
